### ISSUE TITLE
How to add the pinned tab feature?

### ISSUE THREAD

**Issue by connradolisboa** [damiankorcz/Prism-Theme#143]
**What is your request / issue?**
I want to add the minimal pinned tab feature to the current theme I use (minimal). How do I do that?
I use a lot of pinned tabs and was looking around for a long time for it. Funny how by chance I found it and it's not advertised in the theme features,

**Describe the solution you'd like**
Maybe a cssclass? I don't much about it

**Describe alternatives you've considered**
I've asked on Reddit, a guy sent a code to add to a cssclass file but it didn't work
This is the snippet:
.workspace-tab-header:has(.mod-pinned) {
    width: 0;
}

**Additional context**
[The feature]
![image](https://github.com/damiankorcz/Prism-Theme/assets/99513466/7b968622-4e13-497f-9d9c-2cbedbf1de8a)

**Comment by damiankorcz** [comment]
Hi @connradolisboa,
Try the following in a CSS snippet:
```css
.workspace .mod-root .workspace-tab-header[data-type="markdown"]:has(.mod-pinned) .workspace-tab-header-inner-icon,
.workspace .mod-root .workspace-tab-header[data-type="empty"]:has(.mod-pinned) .workspace-tab-header-inner-icon {
    display: flex;
}

.workspace-tab-header:has(.mod-pinned) .workspace-tab-header-inner-title {
    display: none;
}

.workspace .mod-root .workspace-tab-header:has(.mod-pinned),
.workspace-tab-header:has(.mod-pinned) .workspace-tab-header-inner {
    flex: unset;
    width: fit-content;
    min-width: unset;
}
```
I had a quick look with Minimal and it seems to work fine.
