### ISSUE TITLE
Bug: empty status bar looks weird

### ISSUE THREAD

**Issue by chrisgrieser** [damiankorcz/Prism-Theme#157]
If you have nothing in your status bar, there is just this weird blob:

![Pasted image 2024-01-31 at 15 28 47](https://github.com/damiankorcz/Prism-Theme/assets/73286100/28eef96e-a360-462c-b9d6-acd70975dab5)

fix:

```css
.status-bar:empty {
	display: none;
}
```
