### ISSUE TITLE
Add more details to customization steps

### ISSUE THREAD

**Issue by mbbroberg** [damiankorcz/Prism-Theme#171]
**What is your request / issue?**

As a novice to s/css, I can't figure out what of the examples in [this wiki page](https://github.com/damiankorcz/Prism-Theme/wiki/Creating-a-Custom-Colour-Scheme-CSS-Snippet) apply to creating the css snippet necessary to customize. 

**Describe the solution you'd like**
I've created the following file (see below), changed the setting to custom, but don't see an error message and don't see anything changing. 

**Describe alternatives you've considered**
I searched quite a bit to find someone else having a snippet that already works but didn't find one. 

**Additional context**

```css
/* Solarized light theme */
.theme-light.pt-color-scheme-custom-lt {
    --color-grey-base-hsl: 0, 0%, 90%;
    --color-red-base-hsl: 7, 90%, 92%;
    --color-orange-base-hsl: 26, 85%, 89%;
    --color-yellow-base-hsl: 42, 88%, 83%;
    --color-green-base-hsl: 101, 49%, 85%;
    --color-mint-base-hsl: 152, 62%, 85%;
    --color-cyan-base-hsl: 184, 60%, 85%;
    --color-blue-base-hsl: 217, 76%, 92%;
    --color-purple-base-hsl: 251, 87%, 94%;
    --color-pink-base-hsl: 328, 79%, 93%;
    --shadow-color-hsl: 0, 0%, 0%;
    --shadow-s: hsla(var(--shadow-color-hsl), 10%) 0 1px 2px 0;
    --shadow-l: hsla(var(--shadow-color-hsl), 3%) 0 1px 2px, hsla(var(--shadow-color-hsl), 3%) 0 2px 4px, hsla(var(--shadow-color-hsl), 3%) 0 4px 8px, hsla(var(--shadow-color-hsl), 3%) 0 6px 12px;
}

/* Solarized dark theme */
.theme-dark.pt-color-scheme-custom-dt {
    --color-grey-base-hsl: 0, 0%, 16%;
    --color-red-base-hsl: 2, 55%, 19%;
    --color-orange-base-hsl: 26, 65%, 15%;
    --color-yellow-base-hsl: 43, 73%, 12%;
    --color-green-base-hsl: 124, 54%, 12%;
    --color-mint-base-hsl: 165, 88%, 10%;
    --color-cyan-base-hsl: 195, 65%, 13%;
    --color-blue-base-hsl: 225, 50%, 20%;
    --color-purple-base-hsl: 271, 48%, 21%;
    --color-pink-base-hsl: 325, 55%, 18%;
    --shadow-color-hsl: 0, 0%, 0%;
    --shadow-s: hsla(var(--shadow-color-hsl), 10%) 0 1px 2px 0;
    --shadow-l: hsla(var(--shadow-color-hsl), 3%) 0 1px 2px, hsla(var(--shadow-color-hsl), 3%) 0 2px 4px, hsla(var(--shadow-color-hsl), 3%) 0 4px 8px, hsla(var(--shadow-color-hsl), 3%) 0 6px 12px;
}
```
