### ISSUE TITLE
Callout border color, around content section only, displays white

### ISSUE THREAD

**Issue by RedKimberly** [damiankorcz/Prism-Theme#182]
I followed your custom CSS coding to create the example nature callout and another one I created called people. The issue is the bottom border around the content is white instead of color, while the color is correct around the entire border of the callout title. I sincerely apologize if this is a rookie mistake, but I have spent hours searching for a solution. Any help would be greatly appreciated!  

Here is the snippet for the one I created called people that has a pink border around the entire title, but white around the content:

.prism-theme .callout[data-callout="people"] > .callout-title {
    color: var(--color-pink-text);
    background-color: var(--color-pink-base);
    border-color: var(--color-pink-tint);
}

.prism-theme .callout[data-callout="people"] > .callout-title .callout-icon .svg-icon {
    color: var(--color-pink-text);
}

.prism-theme .callout[data-callout="people"] > .callout-content {
    background-color: hsla(var(--color-pink-base-hsl), var(--callout-background-alpha));
    border-color: var(--color-pink-tint);
}

.callout[data-callout="people"] {
    --callout-icon: heart-handshake;
    --callout-color: 224, 27, 185;

Thank you,
Kimberly

**Comment by damiankorcz** [comment]
Hi @RedKimberly,
Looks to me like you did everything right. I haven't had a chance to work on the theme in some time so there is a chance something has changed. When I have some time I'll try and look into a proper solution but for now you can get it working correctly by changing your snippet to this:
```css
.prism-theme .callout[data-callout="people"] > .callout-title {
    color: var(--color-pink-text);
    background-color: var(--color-pink-base);
    border-color: var(--color-pink-tint) !important;
}

.prism-theme .callout[data-callout="people"] > .callout-title .callout-icon .svg-icon {
    color: var(--color-pink-text);
}

.prism-theme .callout[data-callout="people"] > .callout-content {
    background-color: hsla(var(--color-pink-base-hsl), var(--callout-background-alpha));
    border-color: var(--color-pink-tint) !important;
}

.callout[data-callout="people"] {
    --callout-icon: heart-handshake;
    --callout-color: 224, 27, 185;
}
```

**Comment by RedKimberly** [comment]
That fixed it - I should have just reached out to you a long time ago! Thank you for responding so quickly with a fix. I love your Prism theme, so I hope you continue to update it. I've tried several themes and always come back to yours 🙂.

**Comment by damiankorcz** [comment]
Hi @RedKimberly,
Not sure why I haven't closed this issue earlier but I'm just coming around to fixing some other ones and this one seems resolved.

The correct way to do your custom callout from above should be the following if you use the Prism Theme:
```css
.prism-theme:not(.pt-disable-callout-styling) .callout[data-callout="people"] > .callout-title {
    color: var(--color-pink-text);
    background-color: var(--color-pink-base);
    border-color: var(--color-pink-tint);
}

.prism-theme:not(.pt-disable-callout-styling) .callout[data-callout="people"] > .callout-title .callout-icon .svg-icon {
    color: var(--color-pink-text);
}

.prism-theme:not(.pt-disable-callout-styling) .callout[data-callout="people"] > .callout-content {
    background-color: hsla(var(--color-pink-base-hsl), var(--callout-background-alpha));
    border-color: var(--color-pink-tint);
}

.callout[data-callout="people"] {
    --callout-icon: heart-handshake;
    --callout-color: 224, 27, 185;
}
```

and if you happen to be using the [Prism Callout snippet](https://github.com/damiankorcz/Prism-Theme/blob/main/src/snippets/Prism%20Callouts.css) to use Prism callout styling with other themes, then your snippet should look like this:
```css
.prism-callout .callout[data-callout="people"] > .callout-title {
    color: var(--color-pink-text);
    background-color: var(--color-pink-base);
    border-color: var(--color-pink-tint);
}

.prism-callout .callout[data-callout="people"] > .callout-title .callout-icon .svg-icon {
    color: var(--color-pink-text);
}

.prism-callout .callout[data-callout="people"] > .callout-content {
    background-color: hsla(var(--color-pink-base-hsl), var(--callout-background-alpha));
    border-color: var(--color-pink-tint);
}

.callout[data-callout="people"] {
    --callout-icon: heart-handshake;
    --callout-color: 224, 27, 185;
}
```

The Callout Customisation documentation: https://github.com/damiankorcz/Prism-Theme/wiki/Callout-Customisation
