### ISSUE TITLE
How to change the background color of inline code in preview mode?

### ISSUE THREAD

**Issue by IPushedU** [damiankorcz/Prism-Theme#64]
I would like to change the background color of inline code but for the preview mode, so there it is distinguishable by the background/frame (a semi-transparent gray color). I was able to do it for the source view but couldn't find a way for the preview, tried multiple codes.  Currently, it looks like this: 
<img width="178" alt="image" src="https://user-images.githubusercontent.com/43817108/168308046-dbc0fdbe-17e3-4625-9d37-64e0f08fe867.png">
Thanks.

**Comment by damiankorcz** [comment]
Hi @IPushedU,
This snippet should work to change the background colour of inline code in all views. Just keep in mind that the colours used for code are adjusted to work best with the current setup so some might not look right depending on what colour you chose for the background.
```css
.theme-light .cm-s-obsidian span.cm-inline-code,
.theme-light .markdown-rendered code,
.theme-light .cm-s-obsidian span.cm-inline-code:not(.cm-formatting):not(.cm-hmd-indented-code):not(.obsidian-search-match-highlight), {
    background-color: rgba(0,0,0,0.2);
}

.theme-dark .cm-s-obsidian span.cm-inline-code,
.theme-dark .markdown-rendered code,
.theme-dark .cm-s-obsidian span.cm-inline-code:not(.cm-formatting):not(.cm-hmd-indented-code):not(.obsidian-search-match-highlight), {
    background-color: rgba(255,255,255,0.2);
}

/* This is just to prevent the background color from changing in Codeblocks */
pre code {
    background-color: unset !important;
}
```
