### ISSUE TITLE
[FR] Option for file tree indentation

### ISSUE THREAD

**Issue by ShahriarKh** [damiankorcz/Prism-Theme#70]
An option for setting file treee indentation amount is really useful:

![image](https://user-images.githubusercontent.com/31452340/172152204-e2a7c6a1-7427-4791-b468-19046847ecb2.png)
![image](https://user-images.githubusercontent.com/31452340/172152241-3782c81b-8706-49b1-8390-15e2c3d3d9f8.png)

**Describe the solution you'd like**
A simple field in theme settings to control the indentation amount.

**Describe alternatives you've considered**
Adding a custom CSS snippet
```css
.nav-file:not(.mod-root), .nav-folder:not(.mod-root) {
    margin-left: 20px;
}
```
