### ISSUE TITLE
Add support for font options

### ISSUE THREAD

**Issue by ShahriarKh** [damiankorcz/Prism-Theme#79]
Since the theme is using Source Sans as the default font, I think it will be cool to add some options to toggle font features.
For example:
```css
* {
    font-feature-settings: "ss04", "ss03"; /* alternate "g" and "a" glyphs */
    font-variant: slashed-zero;
}
```
This can be done by some simple checkboxes in the Style Settings plugin.
Here you can see all available options: https://beautifulwebtype.com/source-sans-pro/
